-- encoding: UTF-8
INSERT INTO player(username,password,enabled,birth_date,mail,name) VALUES ('Guaje','1111',true,'2002-01-02','guaje@guaje.com','Guaje');
INSERT INTO authorities(id,username,authority) VALUES (1,'Guaje','player');
INSERT INTO player(username,password,enabled,birth_date,mail,name) VALUES ('Antonio','1111',true,'2002-04-04','antonio@antonio.com','Antonio');
INSERT INTO authorities(id,username,authority) VALUES (2,'Antonio','player');
INSERT INTO player(username,password,enabled,birth_date,mail,name) VALUES ('Mera','1',true,'2002-05-05','mera@mera.com','Mera');
INSERT INTO authorities(id,username,authority) VALUES (3,'Mera','player');

INSERT INTO player(username,password,enabled,birth_date,mail,name) VALUES ('admin','1111',true,'2002-01-02','admin@admin.com','admin');
INSERT INTO authorities(id,username,authority) VALUES (4,'admin','admin');

INSERT INTO position(id,x,y) VALUES (1,0,0);
INSERT INTO position(id,x,y) VALUES (2,0,125);
INSERT INTO position(id,x,y) VALUES (3,0,250);
INSERT INTO position(id,x,y) VALUES (4,0,375);
INSERT INTO position(id,x,y) VALUES (6,125,0);
INSERT INTO position(id,x,y) VALUES (7,125,125);
INSERT INTO position(id,x,y) VALUES (8,125,250);
INSERT INTO position(id,x,y) VALUES (9,125,375);
INSERT INTO position(id,x,y) VALUES (11,250,0);
INSERT INTO position(id,x,y) VALUES (12,250,125);
INSERT INTO position(id,x,y) VALUES (13,250,250);
INSERT INTO position(id,x,y) VALUES (14,250,375);
INSERT INTO position(id,x,y) VALUES (16,375,0);
INSERT INTO position(id,x,y) VALUES (17,375,125);
INSERT INTO position(id,x,y) VALUES (18,375,250);
INSERT INTO position(id,x,y) VALUES (19,375,375);

INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (1,'Real Madrid','Madrid','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (2,'Rayo Vallecano','Rayo','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (3,'Fútbol Club Barcelona','Barca','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (4,'Deportivo Alaves','Alaves','Logo','España','M','1',true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (5,'Athletic Club de Bilbao','Bilbao','Logo','España','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (6,'Real Club Celta de Vigo','Celta','Logo','España','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (7,'Real Club Deportivo Espanyol de Barcelona','Espanyol','Logo','España','M',2,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (8,'Unión Deportiva Las Palmas','Palmas','Logo','España','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (9,'Real Club Deportivo Mallorca','Mallorca','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (10,'Club Atlético Osasuna','Osasuna','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (12,'Real Racing Club de Santander','Racing','Logo','España','M',2,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (13,'Real Sociedad','Real','Logo','España','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (14,'Valencia Club de Fútbol','Valencia','Logo','España','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (15,'Real Valladolid Club de Fútbol','Valladolid','Logo','España','M',2,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (16,'Villarreal Club de Fútbol','Villarreal','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (17,'Real Zaragoza','Zaragoza','Logo','España','M',2,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (18,'Atalanta Bergamasca Calcio','Atalanta','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (19,'Associazione Calcio Milan','Milan','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (20,'Società Sportiva Lazio','Lazio','Logo','Italia','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (21,'Associazione Sportiva Roma','Roma','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (22,'Hellas Verona Football Club','Verona','Logo','Italia','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (23,'Società Sportiva Calcio Napoli','Napoli','Logo','Italia','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (24,'Juventus de Turín','Juve','Logo','Italia','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (25,'ACF Fiorentina','Fiore','Logo','Italia','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (26,'Unione Sportiva Lecce','Lecce','Logo','Italia','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (27,'Inter de Milán','Inter','Logo','Italia','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (28,'Bologna Football Club','Bologna','Logo','Italia','M',1,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (29,'Udinese Calcio','Udinese','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (30,'Club Atlético de Madrid','ATM','Logo','España','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (31,'Cagliari Calcio','Cagliari','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (32,'Sevilla Fútbol Club','Sevilla','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (34,'Aston Villa Football Club','AVFC','Logo','Inglaterra','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (35,'Chelsea Football Club','Chelsea','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (36,'Everton Football Club','Everton','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (37,'Liverpool Football Club','Liverpool','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (38,'Manchester City Football Club','City','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (39,'Manchester United Football Club','United','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (40,'Newcastle United Football Club','New','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (41,'Tottenham Hotspur Football Club','Hotspur','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (42,'West Ham United Football Club','Ham','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (43,'Real Sporting de Gijón','Sporting','Logo','España','M',2,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (44,'Unión Deportiva Almería','UDA','Logo','España','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (45,'Cádiz Club de Fútbol','Cadiz','Logo','España','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (46,'Racing Club de Ferrol','Ferrol','Logo','España','M',2,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (47,'Albacete Balompié','Albacete','Logo','España','M',2,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (48,'Sociedad Deportiva Eibar','Eibar','Logo','España','M',2,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (49,'Elche Club de Fútbol','Elche','Logo','España','M',2,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (50,'Torino Football Club','Torino','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (51,'Club Deportivo Leganés','Leganes','Logo','España','M',2,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (52,'Levante Unión Deportiva','Levante','Logo','España','M',2,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (53,'Le Havre Athletic Club','LH','Logo','Francia','M',2,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (54,'Racing Club de Lens','Lens','Logo','Francia','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (55,'Olympique de Lyon','OL','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (56,'Olympique de Marsella','OM','Logo','Francia','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (57,'Football Club de Metz','Metz','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (58,'Association Sportive de Monaco Football Club','Monaco','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (59,'Montpellier Hérault Sport Club','Montpellier','Logo','Francia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (60,'Paris Saint-Germain','PSG','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (61,'Stade Rennes Football Club','Rennes','Logo','Francia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (62,'Racing Club de Estrasburgo Alsacia','RSC','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (63,'Bayern de Múnich','Munich','Logo','Alemania','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (64,'Borussia Dortmund','BVB','Logo','Alemania','M',1,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (65,'Eintracht Fráncfort','Eintracht','Logo','Alemania','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (66,'SC Friburgo','SCF','Logo','Alemania','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (67,'Club Deportivo Tenerife','CDT','Logo','España','M',2,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (68,'Bayer Leverkusen','Bayer','Logo','Alemania','M',1,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (69,'VfB Stuttgart','VFB','Logo','Alemania','M',1,false,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (70,'Real Betis Balompié','Betis','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (71,'Getafe Club de Fútbol','Getafe','Logo','España','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (72,'Werder Bremen','Bremen','Logo','Alemania','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (73,'VfL Wolfsburgo','Wolfsburg','Logo','Alemania','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (74,'Burgos Club de Fútbol','Burgos','Logo','España','M',2,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (75,'Granada Club de Fútbol','Granada','Logo','España','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (76,'F. C. Colonia','Colonia','Logo','Alemania','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (77,'Fútbol Club Cartagena','Cartagena','Logo','España','M',2,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (78,'Toulouse Football Club','Toulouse','Logo','Francia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (79,'Lille Olympique Sporting Club','Lille','Logo','Francia','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (80,'Football Club de Nantes','Nantes','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (81,'VfL Bochum','Bonchum','Logo','Alemania','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (82,'Associazione Calcio Monza','Monza','Logo','Italia','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (83,'Agrupación Deportiva Alcorcón','ADA','Logo','España','M',2,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (84,'Fulham Football Club','Fulham','Logo','Inglaterra','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (85,'Sociedad Deportiva Amorebieta','SDA','Logo','España','M',2,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (86,'Girona Fútbol Club','Girona','Logo','España','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (87,'Club Deportivo Eldense','Eldense','Logo','España','M',2,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (88,'Borussia Mönchengladbach','BM','Logo','Alemania','M',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (89,'Football Club Lorient','Loirent','Logo','Francia','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (90,'1. F.S.V. Mainz 05','Mainz','Logo','Alemania','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (91,'F. C. Union Berlin','Berlin','Logo','Alemania','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (92,'Club Deportivo Mirandés','Mirandes','Logo','España','M',2,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (93,'Stade Brestois 29','Brestois','Logo','Francia','M',1,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (95,'Unione Sportiva Salernitana 1919','Salernitana','Logo','Italia','M',1,false,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (96,'Empoli Football Club','Empoli','Logo','Italia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (97,'Sheffield United Football Club','Shefield','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (98,'Luton Town Football Club','Luton','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (99,'Crystal Palace Football Club','Crystal','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (100,'Burnley Football Club','Burnley','Logo','Inglaterra','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (101,'Genoa Cricket & Football Club','Genoa','Logo','Italia','M',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (102,'Brentford Football Club','Brentford','Logo','Inglaterra','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (103,'Olympique Gymnaste Club de Niza','Niza','Logo','Francia','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (105,'Stade de Reims','Reims','Logo','Francia','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (106,'Nottingham Forest Football Club','Forest','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (107,'SV Darmstadt 98','SVD','Logo','Alemania','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (108,'F. C. Augsburgo','FCA','Logo','Alemania','M',1,false,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (109,'TSG 1899 Hoffenheim','TSG','Logo','Alemania','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (110,'Clermont Foot 63','Clermont','Logo','Francia','M',1,true,false,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (111,'Unione Sportiva Sassuolo Calcio','Sasuolo','Logo','Italia','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (112,'1. FC Heidenheim 1846','FCH','Logo','Alemania','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (113,'AFC Bournemouth','AFCB','Logo','Inglaterra','M',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (114,'Frosinone Calcio','Frosione','Logo','Italia','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (115,'Brighton & Hove Albion Football Club','Brighton','Logo','Inglaterra','M',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (116,'Fútbol Club Andorra','Andorra','Logo','España','M',2,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (117,'RasenBallsport Leipzig','Leipzig','Logo','Alemania','M',1,true,true,true,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (118,'Madrid CFF','CFF','Logo','España','F',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (119,'FC Levante Las Planas', 'LLP','Logo','España','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (121,'Sporting Club De Huelva','Huelva','Logo','España','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (122,'San Diego Wave F','Wave','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (123,'Portland Thorns F','Thorns','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (124,'North Carolina Courage F','NCC','Logo','Estados Unidos','F',1,true,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (126,'Angel City','AG','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (127,'Gothan F','Gothan','Logo','Estados Unidos','F',1,false,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (128,'Orlando Pride','OP','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (129,'Washington Spirit','W','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (130,'Racing Louisville F','RL','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (131,'Houston Dash','HD','Logo','Estados Unidos','F',1,true,false,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (132,'Kansas City Current','KC','Logo','Estados Unidos','F',1,false,true,false,true);
INSERT INTO image(id,name,resource_name,image_type,country,genre,category,has_name,has_initials,has_year,enabled) VALUES (133,'Chicago Red Stars','CRS','Logo','Estados Unidos','F',1,true,false,false,true);